# #############################
# GLOBAL ADI9361 IOSTANDARDS
# #############################
set_property IOSTANDARD LVDS_25  [get_ports {ADI_RX?_LVDS_DOUT_?[?]}]
set_property IOSTANDARD LVDS_25  [get_ports {ADI_TX?_LVDS_DIN_?[?]}]
set_property IOSTANDARD LVCMOS25 [get_ports {CTRL_IN?_2P5_DOUT[?]}]
set_property IOSTANDARD LVCMOS25 [get_ports {CTRL_OUT?_2P5_DIN[?]}]

set_property IOSTANDARD LVCMOS25 [get_ports SCAL_CLK_OUT?_2P5_IN]
set_property IOSTANDARD LVDS_25  [get_ports SCAL_DAT_CLK_OUT?_LVDS_IN_?]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_EN_AGC_IN?_2P5_OUT]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_ENABLE_IN?_2P5_OUT]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_RESET_N_IN?_2P5_OUT]
set_property IOSTANDARD LVDS_25  [get_ports SCAL_FB_CLK_IN?_LVDS_OUT_?]
set_property IOSTANDARD LVDS_25  [get_ports SCAL_RX_FRM_OUT?_LVDS_IN_?]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_SPI_CLK_OUT?_2P5_IN]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_SPI_DI_OUT?_2P5_IN]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_SPI_DO_IN?_2P5_OUT]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_SPI_EN_N_OUT?_2P5_IN]
set_property IOSTANDARD LVDS_25  [get_ports SCAL_TX_FRM_IN?_LVDS_OUT_?]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_TXNRX_IN?_2P5_OUT]

set_property DIFF_TERM TRUE [get_ports SCAL_DAT_CLK_OUT?_LVDS_IN_?]
set_property DIFF_TERM TRUE [get_ports SCAL_RX_FRM_OUT?_LVDS_IN_?]
set_property DIFF_TERM TRUE [get_ports ADI_TX?_LVDS_DIN_?]

# #############################
# AD9361 XCVR 0 signals
# #############################
set_property PACKAGE_PIN M7     [get_ports {ADI_RX0_LVDS_DOUT_P[0]}]
set_property PACKAGE_PIN M5     [get_ports {ADI_RX0_LVDS_DOUT_P[1]}]
set_property PACKAGE_PIN N1     [get_ports {ADI_RX0_LVDS_DOUT_P[2]}]
set_property PACKAGE_PIN P9     [get_ports {ADI_RX0_LVDS_DOUT_P[3]}]
set_property PACKAGE_PIN P6     [get_ports {ADI_RX0_LVDS_DOUT_P[4]}]
set_property PACKAGE_PIN N9     [get_ports {ADI_RX0_LVDS_DOUT_P[5]}]
set_property PACKAGE_PIN R1     [get_ports {ADI_TX0_LVDS_DIN_P[0]}]
set_property PACKAGE_PIN P4     [get_ports {ADI_TX0_LVDS_DIN_P[1]}]
set_property PACKAGE_PIN T3     [get_ports {ADI_TX0_LVDS_DIN_P[2]}]
set_property PACKAGE_PIN T5     [get_ports {ADI_TX0_LVDS_DIN_P[3]}]
set_property PACKAGE_PIN R6     [get_ports {ADI_TX0_LVDS_DIN_P[4]}]
set_property PACKAGE_PIN N3     [get_ports {ADI_TX0_LVDS_DIN_P[5]}]
set_property PACKAGE_PIN U2     [get_ports {CTRL_IN0_2P5_DOUT[0]}]
set_property PACKAGE_PIN R11    [get_ports {CTRL_IN0_2P5_DOUT[1]}]
set_property PACKAGE_PIN R2     [get_ports {CTRL_IN0_2P5_DOUT[2]}]
set_property PACKAGE_PIN R3     [get_ports {CTRL_IN0_2P5_DOUT[3]}]
set_property PACKAGE_PIN P10    [get_ports {CTRL_OUT0_2P5_DIN[0]}]
set_property PACKAGE_PIN U6     [get_ports {CTRL_OUT0_2P5_DIN[1]}]
set_property PACKAGE_PIN T8     [get_ports {CTRL_OUT0_2P5_DIN[2]}]
set_property PACKAGE_PIN Y10    [get_ports {CTRL_OUT0_2P5_DIN[3]}]
set_property PACKAGE_PIN U7     [get_ports {CTRL_OUT0_2P5_DIN[4]}]
set_property PACKAGE_PIN W10    [get_ports {CTRL_OUT0_2P5_DIN[5]}]
set_property PACKAGE_PIN T7     [get_ports {CTRL_OUT0_2P5_DIN[6]}]
set_property PACKAGE_PIN R10    [get_ports {CTRL_OUT0_2P5_DIN[7]}]
set_property PACKAGE_PIN AB4    [get_ports SCAL_CLK_OUT0_2P5_IN]
set_property PACKAGE_PIN P5     [get_ports SCAL_DAT_CLK_OUT0_LVDS_IN_P]
set_property PACKAGE_PIN U1     [get_ports SCAL_EN_AGC_IN0_2P5_OUT]
set_property PACKAGE_PIN W8     [get_ports SCAL_ENABLE_IN0_2P5_OUT]
set_property PACKAGE_PIN U10    [get_ports SCAL_FB_CLK_IN0_LVDS_OUT_P]
set_property PACKAGE_PIN V9     [get_ports SCAL_RESET_N_IN0_2P5_OUT]
set_property PACKAGE_PIN R8     [get_ports SCAL_RX_FRM_OUT0_LVDS_IN_P]
set_property PACKAGE_PIN U4     [get_ports SCAL_SPI_CLK_OUT0_2P5_IN]
set_property PACKAGE_PIN W9     [get_ports SCAL_SPI_DI_OUT0_2P5_IN]
set_property PACKAGE_PIN V2     [get_ports SCAL_SPI_DO_IN0_2P5_OUT]
set_property PACKAGE_PIN U11    [get_ports SCAL_SPI_EN_N_OUT0_2P5_IN]
set_property PACKAGE_PIN U9     [get_ports SCAL_TX_FRM_IN0_LVDS_OUT_P]
set_property PACKAGE_PIN U5     [get_ports SCAL_TXNRX_IN0_2P5_OUT]


# #############################
# AD9361 XCVR 1 signals
# #############################
set_property PACKAGE_PIN H11    [get_ports {ADI_RX1_LVDS_DOUT_P[0]}]
set_property PACKAGE_PIN K10    [get_ports {ADI_RX1_LVDS_DOUT_P[1]}]
set_property PACKAGE_PIN K7     [get_ports {ADI_RX1_LVDS_DOUT_P[2]}]
set_property PACKAGE_PIN J4     [get_ports {ADI_RX1_LVDS_DOUT_P[3]}]
set_property PACKAGE_PIN G10    [get_ports {ADI_RX1_LVDS_DOUT_P[4]}]
set_property PACKAGE_PIN H1     [get_ports {ADI_RX1_LVDS_DOUT_P[5]}]
set_property PACKAGE_PIN G7     [get_ports {ADI_TX1_LVDS_DIN_P[0]}]
set_property PACKAGE_PIN L5     [get_ports {ADI_TX1_LVDS_DIN_P[1]}]
set_property PACKAGE_PIN K11    [get_ports {ADI_TX1_LVDS_DIN_P[2]}]
set_property PACKAGE_PIN H9     [get_ports {ADI_TX1_LVDS_DIN_P[3]}]
set_property PACKAGE_PIN F3     [get_ports {ADI_TX1_LVDS_DIN_P[4]}]
set_property PACKAGE_PIN L12    [get_ports {ADI_TX1_LVDS_DIN_P[5]}]
set_property PACKAGE_PIN J5     [get_ports {CTRL_IN1_2P5_DOUT[0]}]
set_property PACKAGE_PIN H12    [get_ports {CTRL_IN1_2P5_DOUT[1]}]
set_property PACKAGE_PIN J8     [get_ports {CTRL_IN1_2P5_DOUT[2]}]
set_property PACKAGE_PIN H7     [get_ports {CTRL_IN1_2P5_DOUT[3]}]
set_property PACKAGE_PIN M10    [get_ports {CTRL_OUT1_2P5_DIN[0]}]
set_property PACKAGE_PIN M11    [get_ports {CTRL_OUT1_2P5_DIN[1]}]
set_property PACKAGE_PIN N8     [get_ports {CTRL_OUT1_2P5_DIN[2]}]
set_property PACKAGE_PIN L4     [get_ports {CTRL_OUT1_2P5_DIN[3]}]
set_property PACKAGE_PIN H6     [get_ports {CTRL_OUT1_2P5_DIN[4]}]
set_property PACKAGE_PIN J9     [get_ports {CTRL_OUT1_2P5_DIN[5]}]
set_property PACKAGE_PIN N7     [get_ports {CTRL_OUT1_2P5_DIN[6]}]
set_property PACKAGE_PIN H4     [get_ports {CTRL_OUT1_2P5_DIN[7]}]
set_property PACKAGE_PIN J6     [get_ports SCAL_CLK_OUT1_2P5_IN]
set_property PACKAGE_PIN G5     [get_ports SCAL_DAT_CLK_OUT1_LVDS_IN_P]
set_property PACKAGE_PIN K2     [get_ports SCAL_EN_AGC_IN1_2P5_OUT]
set_property PACKAGE_PIN L7     [get_ports SCAL_ENABLE_IN1_2P5_OUT]
set_property PACKAGE_PIN L8     [get_ports SCAL_FB_CLK_IN1_LVDS_OUT_P]
set_property PACKAGE_PIN L3     [get_ports SCAL_RESET_N_IN1_2P5_OUT]
set_property PACKAGE_PIN M2     [get_ports SCAL_RX_FRM_OUT1_LVDS_IN_P]
set_property PACKAGE_PIN H2     [get_ports SCAL_SPI_CLK_OUT1_2P5_IN]
set_property PACKAGE_PIN J1     [get_ports SCAL_SPI_DI_OUT1_2P5_IN]
set_property PACKAGE_PIN G2     [get_ports SCAL_SPI_DO_IN1_2P5_OUT]
set_property PACKAGE_PIN H3     [get_ports SCAL_SPI_EN_N_OUT1_2P5_IN]
set_property PACKAGE_PIN L10    [get_ports SCAL_TX_FRM_IN1_LVDS_OUT_P]
set_property PACKAGE_PIN K1     [get_ports SCAL_TXNRX_IN1_2P5_OUT]


# #############################
# AD9361 XCVR 2 signals
# #############################
set_property PACKAGE_PIN K30    [get_ports {ADI_RX2_LVDS_DOUT_P[0]}]
set_property PACKAGE_PIN H31    [get_ports {ADI_RX2_LVDS_DOUT_P[1]}]
set_property PACKAGE_PIN K23    [get_ports {ADI_RX2_LVDS_DOUT_P[2]}]
set_property PACKAGE_PIN G24    [get_ports {ADI_RX2_LVDS_DOUT_P[3]}]
set_property PACKAGE_PIN L28    [get_ports {ADI_RX2_LVDS_DOUT_P[4]}]
set_property PACKAGE_PIN K31    [get_ports {ADI_RX2_LVDS_DOUT_P[5]}]
set_property PACKAGE_PIN M24    [get_ports {ADI_TX2_LVDS_DIN_P[0]}]
set_property PACKAGE_PIN M25    [get_ports {ADI_TX2_LVDS_DIN_P[1]}]
set_property PACKAGE_PIN G29    [get_ports {ADI_TX2_LVDS_DIN_P[2]}]
set_property PACKAGE_PIN L27    [get_ports {ADI_TX2_LVDS_DIN_P[3]}]
set_property PACKAGE_PIN K25    [get_ports {ADI_TX2_LVDS_DIN_P[4]}]
set_property PACKAGE_PIN J24    [get_ports {ADI_TX2_LVDS_DIN_P[5]}]
set_property PACKAGE_PIN J26    [get_ports {CTRL_IN2_2P5_DOUT[0]}]
set_property PACKAGE_PIN H28    [get_ports {CTRL_IN2_2P5_DOUT[1]}]
set_property PACKAGE_PIN G26    [get_ports {CTRL_IN2_2P5_DOUT[2]}]
set_property PACKAGE_PIN K26    [get_ports {CTRL_IN2_2P5_DOUT[3]}]
set_property PACKAGE_PIN L29    [get_ports {CTRL_OUT2_2P5_DIN[0]}]
set_property PACKAGE_PIN L33    [get_ports {CTRL_OUT2_2P5_DIN[1]}]
set_property PACKAGE_PIN L23    [get_ports {CTRL_OUT2_2P5_DIN[2]}]
set_property PACKAGE_PIN H27    [get_ports {CTRL_OUT2_2P5_DIN[3]}]
set_property PACKAGE_PIN L34    [get_ports {CTRL_OUT2_2P5_DIN[4]}]
set_property PACKAGE_PIN R26    [get_ports {CTRL_OUT2_2P5_DIN[5]}]
set_property PACKAGE_PIN G27    [get_ports {CTRL_OUT2_2P5_DIN[6]}]
set_property PACKAGE_PIN H26    [get_ports {CTRL_OUT2_2P5_DIN[7]}]
set_property PACKAGE_PIN J28    [get_ports SCAL_CLK_OUT2_2P5_IN]
set_property PACKAGE_PIN J29    [get_ports SCAL_DAT_CLK_OUT2_LVDS_IN_P]
set_property PACKAGE_PIN H32    [get_ports SCAL_EN_AGC_IN2_2P5_OUT]
set_property PACKAGE_PIN L30    [get_ports SCAL_ENABLE_IN2_2P5_OUT]
set_property PACKAGE_PIN K33    [get_ports SCAL_FB_CLK_IN2_LVDS_OUT_P]
set_property PACKAGE_PIN G34    [get_ports SCAL_RESET_N_IN2_2P5_OUT]
set_property PACKAGE_PIN J33    [get_ports SCAL_RX_FRM_OUT2_LVDS_IN_P]
set_property PACKAGE_PIN P26    [get_ports SCAL_SPI_CLK_OUT2_2P5_IN]
set_property PACKAGE_PIN T24    [get_ports SCAL_SPI_DI_OUT2_2P5_IN]
set_property PACKAGE_PIN M26    [get_ports SCAL_SPI_DO_IN2_2P5_OUT]
set_property PACKAGE_PIN H33    [get_ports SCAL_SPI_EN_N_OUT2_2P5_IN]
set_property PACKAGE_PIN L32    [get_ports SCAL_TX_FRM_IN2_LVDS_OUT_P]
set_property PACKAGE_PIN M27    [get_ports SCAL_TXNRX_IN2_2P5_OUT]


# #############################
# AD9361 XCVR 3 signals
# #############################
set_property PACKAGE_PIN R25    [get_ports {ADI_RX3_LVDS_DOUT_P[0]}]
set_property PACKAGE_PIN U29    [get_ports {ADI_RX3_LVDS_DOUT_P[1]}]
set_property PACKAGE_PIN R31    [get_ports {ADI_RX3_LVDS_DOUT_P[2]}]
set_property PACKAGE_PIN N31    [get_ports {ADI_RX3_LVDS_DOUT_P[3]}]
set_property PACKAGE_PIN U25    [get_ports {ADI_RX3_LVDS_DOUT_P[4]}]
set_property PACKAGE_PIN P24    [get_ports {ADI_RX3_LVDS_DOUT_P[5]}]
set_property PACKAGE_PIN M30    [get_ports {ADI_TX3_LVDS_DIN_P[0]}]
set_property PACKAGE_PIN T32    [get_ports {ADI_TX3_LVDS_DIN_P[1]}]
set_property PACKAGE_PIN U26    [get_ports {ADI_TX3_LVDS_DIN_P[2]}]
set_property PACKAGE_PIN T28    [get_ports {ADI_TX3_LVDS_DIN_P[3]}]
set_property PACKAGE_PIN P28    [get_ports {ADI_TX3_LVDS_DIN_P[4]}]
set_property PACKAGE_PIN U31    [get_ports {ADI_TX3_LVDS_DIN_P[5]}]
set_property PACKAGE_PIN N26    [get_ports {CTRL_IN3_2P5_DOUT[0]}]
set_property PACKAGE_PIN N28    [get_ports {CTRL_IN3_2P5_DOUT[1]}]
set_property PACKAGE_PIN AD33   [get_ports {CTRL_IN3_2P5_DOUT[2]}]
set_property PACKAGE_PIN AE31   [get_ports {CTRL_IN3_2P5_DOUT[3]}]
set_property PACKAGE_PIN N32    [get_ports {CTRL_OUT3_2P5_DIN[0]}]
set_property PACKAGE_PIN AD30   [get_ports {CTRL_OUT3_2P5_DIN[1]}]
set_property PACKAGE_PIN N29    [get_ports {CTRL_OUT3_2P5_DIN[2]}]
set_property PACKAGE_PIN AE30   [get_ports {CTRL_OUT3_2P5_DIN[3]}]
set_property PACKAGE_PIN AG32   [get_ports {CTRL_OUT3_2P5_DIN[4]}]
set_property PACKAGE_PIN N27    [get_ports {CTRL_OUT3_2P5_DIN[5]}]
set_property PACKAGE_PIN M29    [get_ports {CTRL_OUT3_2P5_DIN[6]}]
set_property PACKAGE_PIN AF33   [get_ports {CTRL_OUT3_2P5_DIN[7]}]
set_property PACKAGE_PIN U30    [get_ports SCAL_CLK_OUT3_2P5_IN]
set_property PACKAGE_PIN R30    [get_ports SCAL_DAT_CLK_OUT3_LVDS_IN_P]
set_property PACKAGE_PIN AG34   [get_ports SCAL_EN_AGC_IN3_2P5_OUT]
set_property PACKAGE_PIN P34    [get_ports SCAL_ENABLE_IN3_2P5_OUT]
set_property PACKAGE_PIN U34    [get_ports SCAL_FB_CLK_IN3_LVDS_OUT_P]
set_property PACKAGE_PIN M34    [get_ports SCAL_RESET_N_IN3_2P5_OUT]
set_property PACKAGE_PIN T27    [get_ports SCAL_RX_FRM_OUT3_LVDS_IN_P]
set_property PACKAGE_PIN N33    [get_ports SCAL_SPI_CLK_OUT3_2P5_IN]
set_property PACKAGE_PIN AE33   [get_ports SCAL_SPI_DI_OUT3_2P5_IN]
set_property PACKAGE_PIN AD23   [get_ports SCAL_SPI_DO_IN3_2P5_OUT]
set_property PACKAGE_PIN U24    [get_ports SCAL_SPI_EN_N_OUT3_2P5_IN]
set_property PACKAGE_PIN T33    [get_ports SCAL_TX_FRM_IN3_LVDS_OUT_P]
set_property PACKAGE_PIN P33    [get_ports SCAL_TXNRX_IN3_2P5_OUT]


# #############################
# AD9361 XCVR 4 signals
# #############################
set_property PACKAGE_PIN AA3    [get_ports {ADI_RX4_LVDS_DOUT_P[0]}]
set_property PACKAGE_PIN AC7    [get_ports {ADI_RX4_LVDS_DOUT_P[1]}]
set_property PACKAGE_PIN V7     [get_ports {ADI_RX4_LVDS_DOUT_P[2]}]
set_property PACKAGE_PIN AB10   [get_ports {ADI_RX4_LVDS_DOUT_P[3]}]
set_property PACKAGE_PIN V4     [get_ports {ADI_RX4_LVDS_DOUT_P[4]}]
set_property PACKAGE_PIN W6     [get_ports {ADI_RX4_LVDS_DOUT_P[5]}]
set_property PACKAGE_PIN W1     [get_ports {ADI_TX4_LVDS_DIN_P[0]}]
set_property PACKAGE_PIN W5     [get_ports {ADI_TX4_LVDS_DIN_P[1]}]
set_property PACKAGE_PIN AB2    [get_ports {ADI_TX4_LVDS_DIN_P[2]}]
set_property PACKAGE_PIN AB7    [get_ports {ADI_TX4_LVDS_DIN_P[3]}]
set_property PACKAGE_PIN Y8     [get_ports {ADI_TX4_LVDS_DIN_P[4]}]
set_property PACKAGE_PIN AC4    [get_ports {ADI_TX4_LVDS_DIN_P[5]}]
set_property PACKAGE_PIN AD24   [get_ports {CTRL_IN4_2P5_DOUT[0]}]
set_property PACKAGE_PIN V3     [get_ports {CTRL_IN4_2P5_DOUT[1]}]
set_property PACKAGE_PIN AA8    [get_ports {CTRL_IN4_2P5_DOUT[2]}]
set_property PACKAGE_PIN AC24   [get_ports {CTRL_IN4_2P5_DOUT[3]}]
set_property PACKAGE_PIN AA7    [get_ports {CTRL_OUT4_2P5_DIN[0]}]
set_property PACKAGE_PIN AF24   [get_ports {CTRL_OUT4_2P5_DIN[1]}]
set_property PACKAGE_PIN AF23   [get_ports {CTRL_OUT4_2P5_DIN[2]}]
set_property PACKAGE_PIN AE23   [get_ports {CTRL_OUT4_2P5_DIN[3]}]
set_property PACKAGE_PIN Y11    [get_ports {CTRL_OUT4_2P5_DIN[4]}]
set_property PACKAGE_PIN AC9    [get_ports {CTRL_OUT4_2P5_DIN[5]}]
set_property PACKAGE_PIN W3     [get_ports {CTRL_OUT4_2P5_DIN[6]}]
set_property PACKAGE_PIN V8     [get_ports {CTRL_OUT4_2P5_DIN[7]}]
set_property PACKAGE_PIN AB5    [get_ports SCAL_CLK_OUT4_2P5_IN]
set_property PACKAGE_PIN AA5    [get_ports SCAL_DAT_CLK_OUT4_LVDS_IN_P]
set_property PACKAGE_PIN AG24   [get_ports SCAL_EN_AGC_IN4_2P5_OUT]
set_property PACKAGE_PIN AH24   [get_ports SCAL_ENABLE_IN4_2P5_OUT]
set_property PACKAGE_PIN AA10   [get_ports SCAL_FB_CLK_IN4_LVDS_OUT_P]
set_property PACKAGE_PIN AG25   [get_ports SCAL_RESET_N_IN4_2P5_OUT]
set_property PACKAGE_PIN Y3     [get_ports SCAL_RX_FRM_OUT4_LVDS_IN_P]
set_property PACKAGE_PIN AF25   [get_ports SCAL_SPI_CLK_OUT4_2P5_IN]
set_property PACKAGE_PIN AB11   [get_ports SCAL_SPI_DI_OUT4_2P5_IN]
set_property PACKAGE_PIN AD25   [get_ports SCAL_SPI_DO_IN4_2P5_OUT]
set_property PACKAGE_PIN AE25   [get_ports SCAL_SPI_EN_N_OUT4_2P5_IN]
set_property PACKAGE_PIN AC2    [get_ports SCAL_TX_FRM_IN4_LVDS_OUT_P]
set_property PACKAGE_PIN AC8    [get_ports SCAL_TXNRX_IN4_2P5_OUT]


# #############################
# ARM/SoC signals
# #############################
#set_property DRIVE 12            [get_ports GPMC_BE_N]
#set_property SLEW SLOW           [get_ports GPMC_BE_N]
#set_property DRIVE 12            [get_ports GPMC_CS_N]
#set_property SLEW SLOW           [get_ports GPMC_CS_N]
#set_property DRIVE 12            [get_ports GPMC_WAIT]
#set_property SLEW SLOW           [get_ports GPMC_WAIT]

set_property IOSTANDARD LVCMOS33 [get_ports GPMC_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports {GPMC_AD[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPMC_A[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports GPMC_CE_N]
set_property IOSTANDARD LVCMOS33 [get_ports GPMC_RE_N]
set_property IOSTANDARD LVCMOS33 [get_ports GPMC_WE_N]
set_property IOSTANDARD LVCMOS33 [get_ports GPMC_CLE]
set_property IOSTANDARD LVCMOS33 [get_ports GPMC_ALE]
set_property IOSTANDARD LVCMOS33 [get_ports GPMC_BE_N]
set_property IOSTANDARD LVCMOS33 [get_ports GPMC_CS_N]
set_property IOSTANDARD LVCMOS33 [get_ports GPMC_WAIT]
set_property PACKAGE_PIN V33     [get_ports {GPMC_AD[0]}]
set_property PACKAGE_PIN Y33     [get_ports {GPMC_AD[1]}]
set_property PACKAGE_PIN W34     [get_ports {GPMC_AD[2]}]
set_property PACKAGE_PIN Y32     [get_ports {GPMC_AD[3]}]
set_property PACKAGE_PIN AC34    [get_ports {GPMC_AD[4]}]
set_property PACKAGE_PIN AC33    [get_ports {GPMC_AD[5]}]
set_property PACKAGE_PIN AA33    [get_ports {GPMC_AD[6]}]
set_property PACKAGE_PIN AA32    [get_ports {GPMC_AD[7]}]
set_property PACKAGE_PIN AC32    [get_ports {GPMC_AD[8]}]
set_property PACKAGE_PIN AC31    [get_ports {GPMC_AD[9]}]
set_property PACKAGE_PIN AB34    [get_ports {GPMC_AD[10]}]
set_property PACKAGE_PIN AA34    [get_ports {GPMC_AD[11]}]
set_property PACKAGE_PIN AC29    [get_ports {GPMC_AD[12]}]
set_property PACKAGE_PIN AC28    [get_ports {GPMC_AD[13]}]
set_property PACKAGE_PIN AA28    [get_ports {GPMC_AD[14]}]
set_property PACKAGE_PIN AA27    [get_ports {GPMC_AD[15]}]
set_property PACKAGE_PIN Y28     [get_ports {GPMC_A[16]}]
set_property PACKAGE_PIN W33     [get_ports {GPMC_A[17]}]
set_property PACKAGE_PIN W28     [get_ports {GPMC_A[18]}]
set_property PACKAGE_PIN V26     [get_ports GPMC_ALE]
set_property PACKAGE_PIN AB26    [get_ports GPMC_BE_N]
set_property PACKAGE_PIN V34     [get_ports GPMC_CE_N]
set_property PACKAGE_PIN W29     [get_ports GPMC_CLE]
set_property PACKAGE_PIN Y30     [get_ports GPMC_CLK]
set_property PACKAGE_PIN W31     [get_ports GPMC_CS_N]
set_property PACKAGE_PIN W25     [get_ports GPMC_RE_N]
set_property PACKAGE_PIN Y25     [get_ports GPMC_WAIT]
set_property PACKAGE_PIN Y26     [get_ports GPMC_WE_N]

set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_RXCLK]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_TXCLK]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_RXER]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_CRS]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_TXEN]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_RXDV]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_COL]
set_property IOSTANDARD LVCMOS33 [get_ports {AM3357_GMII2_RXD[?]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AM3357_GMII2_TXD[?]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AM3357_GPIO_2[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AM3357_GPIO_3[*]}]
set_property PACKAGE_PIN AJ29    [get_ports AM3357_GMII2_RXCLK]
set_property PACKAGE_PIN AL30    [get_ports AM3357_GMII2_TXCLK]
set_property PACKAGE_PIN AJ33    [get_ports AM3357_GMII2_RXER]
set_property PACKAGE_PIN AN34    [get_ports AM3357_GMII2_CRS]
set_property PACKAGE_PIN AK33    [get_ports AM3357_GMII2_TXEN]
set_property PACKAGE_PIN AN33    [get_ports AM3357_GMII2_RXDV]
set_property PACKAGE_PIN AK32    [get_ports AM3357_GMII2_COL]
set_property PACKAGE_PIN AP34    [get_ports {AM3357_GMII2_RXD[0]}]
set_property PACKAGE_PIN AL34    [get_ports {AM3357_GMII2_RXD[1]}]
set_property PACKAGE_PIN AN32    [get_ports {AM3357_GMII2_RXD[2]}]
set_property PACKAGE_PIN AL33    [get_ports {AM3357_GMII2_RXD[3]}]
set_property PACKAGE_PIN AJ31    [get_ports {AM3357_GMII2_TXD[0]}]
set_property PACKAGE_PIN AM32    [get_ports {AM3357_GMII2_TXD[1]}]
set_property PACKAGE_PIN AM34    [get_ports {AM3357_GMII2_TXD[2]}]
set_property PACKAGE_PIN AK31    [get_ports {AM3357_GMII2_TXD[3]}]
set_property PACKAGE_PIN AM31    [get_ports {AM3357_GPIO_2[22]}]
set_property PACKAGE_PIN AL32    [get_ports {AM3357_GPIO_2[23]}]
set_property PACKAGE_PIN V27     [get_ports {AM3357_GPIO_2[24]}]
set_property PACKAGE_PIN AB31    [get_ports {AM3357_GPIO_2[25]}]
set_property PACKAGE_PIN AJ30    [get_ports {AM3357_GPIO_3[17]}]
set_property PACKAGE_PIN AJ24    [get_ports {AM3357_GPIO_3[18]}]


# #############################
# CPRI signals
# #############################
set_property IOSTANDARD LVCMOS33 [get_ports CPRI0_SFP_RS]
set_property IOSTANDARD LVCMOS33 [get_ports CPRI?_SFP_TX_FAULT]
set_property IOSTANDARD LVCMOS33 [get_ports CPRI?_SFP_LOS]
set_property IOSTANDARD LVCMOS33 [get_ports CPRI?_SFP_TX_DISABLE]
set_property IOSTANDARD LVCMOS33 [get_ports CPRI?_SFP_ABSENT]
set_property IOSTANDARD LVCMOS33 [get_ports CPRI?_SFP_RS]

set_property PACKAGE_PIN AL3  [get_ports CPRI0_SFP_RS]
set_property PACKAGE_PIN AL4  [get_ports CPRI0_SFP_TX_FAULT]
set_property PACKAGE_PIN AK1  [get_ports CPRI0_SFP_LOS]
set_property PACKAGE_PIN AK2  [get_ports CPRI0_SFP_TX_DISABLE]
set_property PACKAGE_PIN AN1  [get_ports CPRI0_SFP_ABSENT]

set_property PACKAGE_PIN AK13 [get_ports CPRI0_OPTICAL_RX_N]
set_property PACKAGE_PIN AP13 [get_ports CPRI0_OPTICAL_TX_N]


# #############################
# CLOCK signals
# #############################
set_property IOSTANDARD LVDS_25  [get_ports CLK_LVDS_FPGA_122MHZ88_1_?]
set_property PACKAGE_PIN AG29    [get_ports CLK_LVDS_FPGA_122MHZ88_1_P]
set_property PACKAGE_PIN AH14    [get_ports CLK_LVDS_FPGA_122MHZ88_0_N]

set_property IOSTANDARD LVDS_25  [get_ports CLK_LVDS_FPGA1_30MHZ72_?]
set_property PACKAGE_PIN AH28    [get_ports CLK_LVDS_FPGA1_30MHZ72_P]

set_property IOSTANDARD LVCMOS33 [get_ports CLK_25MHZ_FPGA]
set_property PACKAGE_PIN AE5     [get_ports CLK_25MHZ_FPGA]

set_property IOSTANDARD LVDS_25 [get_ports REC_CLK_30P72MHZ_?]
set_property PACKAGE_PIN AF29 [get_ports REC_CLK_30P72MHZ_P]


# #############################
# SPI signals
# #############################
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_MUX_SEL[?]}]
set_property PACKAGE_PIN AE11    [get_ports {SPI_MUX_SEL[0]}]
set_property PACKAGE_PIN AD11    [get_ports {SPI_MUX_SEL[1]}]
set_property PACKAGE_PIN AH11    [get_ports {SPI_MUX_SEL[2]}]
set_property PACKAGE_PIN AG11    [get_ports {SPI_MUX_SEL[3]}]
set_property PACKAGE_PIN AE10    [get_ports {SPI_MUX_SEL[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SPI_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SPI_CSN]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SPI_MISO]
set_property PACKAGE_PIN W30     [get_ports FPGA_SPI_SCK]
set_property PACKAGE_PIN Y27     [get_ports FPGA_SPI_CSN]
set_property PACKAGE_PIN V29     [get_ports FPGA_SPI_MOSI]
set_property PACKAGE_PIN V28     [get_ports FPGA_SPI_MISO]


# #############################
# MICTOR signals
# #############################
# set_property IOSTANDARD LVCMOS33 [get_ports FPGA_DEBUG_MIC_CLK_IN]
# set_property PACKAGE_PIN AK28    [get_ports FPGA_DEBUG_MIC_CLK_IN]

set_property IOSTANDARD LVCMOS33 [get_ports FPGA_DEBUG_MIC_CLK]
set_property PACKAGE_PIN AK25    [get_ports FPGA_DEBUG_MIC_CLK]

set_property IOSTANDARD LVCMOS33 [get_ports FPGA_DEBUG_MICB_CLK]
set_property PACKAGE_PIN AH8     [get_ports FPGA_DEBUG_MICB_CLK]

set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_DEBUG_MICA[*]}]
set_property PACKAGE_PIN AN8     [get_ports {FPGA_DEBUG_MICA[0]}]
set_property PACKAGE_PIN AP10    [get_ports {FPGA_DEBUG_MICA[1]}]
set_property PACKAGE_PIN AN9     [get_ports {FPGA_DEBUG_MICA[2]}]
set_property PACKAGE_PIN AK11    [get_ports {FPGA_DEBUG_MICA[3]}]
set_property PACKAGE_PIN AL27    [get_ports {FPGA_DEBUG_MICA[4]}]
set_property PACKAGE_PIN AP29    [get_ports {FPGA_DEBUG_MICA[5]}]
set_property PACKAGE_PIN AM9     [get_ports {FPGA_DEBUG_MICA[6]}]
set_property PACKAGE_PIN AN6     [get_ports {FPGA_DEBUG_MICA[7]}]
set_property PACKAGE_PIN AJ28    [get_ports {FPGA_DEBUG_MICA[8]}]
set_property PACKAGE_PIN AK27    [get_ports {FPGA_DEBUG_MICA[9]}]
set_property PACKAGE_PIN AN11    [get_ports {FPGA_DEBUG_MICA[10]}]
set_property PACKAGE_PIN AP11    [get_ports {FPGA_DEBUG_MICA[11]}]
set_property PACKAGE_PIN AP28    [get_ports {FPGA_DEBUG_MICA[12]}]
set_property PACKAGE_PIN AJ8     [get_ports {FPGA_DEBUG_MICA[13]}]
set_property PACKAGE_PIN AM10    [get_ports {FPGA_DEBUG_MICA[14]}]
set_property PACKAGE_PIN AP30    [get_ports {FPGA_DEBUG_MICA[15]}]
set_property PACKAGE_PIN AK10    [get_ports {FPGA_DEBUG_MICA[16]}]
set_property PACKAGE_PIN AL10    [get_ports {FPGA_DEBUG_MICA[17]}]
set_property PACKAGE_PIN AM29    [get_ports {FPGA_DEBUG_MICA[18]}]
set_property PACKAGE_PIN AJ25    [get_ports {FPGA_DEBUG_MICA[19]}]
set_property PACKAGE_PIN AL9     [get_ports {FPGA_DEBUG_MICA[20]}]
set_property PACKAGE_PIN AJ10    [get_ports {FPGA_DEBUG_MICA[21]}]
set_property PACKAGE_PIN AL28    [get_ports {FPGA_DEBUG_MICA[22]}]
set_property PACKAGE_PIN AM11    [get_ports {FPGA_DEBUG_MICA[23]}]
set_property PACKAGE_PIN AK26    [get_ports {FPGA_DEBUG_MICA[24]}]
set_property PACKAGE_PIN AN29    [get_ports {FPGA_DEBUG_MICA[25]}]
set_property PACKAGE_PIN AP9     [get_ports {FPGA_DEBUG_MICA[26]}]
set_property PACKAGE_PIN AJ11    [get_ports {FPGA_DEBUG_MICA[27]}]
set_property PACKAGE_PIN AN28    [get_ports {FPGA_DEBUG_MICA[28]}]
set_property PACKAGE_PIN AL8     [get_ports {FPGA_DEBUG_MICA[29]}]
set_property PACKAGE_PIN AP8     [get_ports {FPGA_DEBUG_MICA[30]}]
set_property PACKAGE_PIN AN7     [get_ports {FPGA_DEBUG_MICA[31]}]

set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_DEBUG_MICB[*]}]
set_property PACKAGE_PIN AF4     [get_ports {FPGA_DEBUG_MICB[0]}]
set_property PACKAGE_PIN AG4     [get_ports {FPGA_DEBUG_MICB[1]}]
set_property PACKAGE_PIN AH3     [get_ports {FPGA_DEBUG_MICB[2]}]
set_property PACKAGE_PIN AJ3     [get_ports {FPGA_DEBUG_MICB[3]}]
set_property PACKAGE_PIN AF3     [get_ports {FPGA_DEBUG_MICB[4]}]
set_property PACKAGE_PIN AG2     [get_ports {FPGA_DEBUG_MICB[5]}]
set_property PACKAGE_PIN AE2     [get_ports {FPGA_DEBUG_MICB[6]}]
set_property PACKAGE_PIN AF2     [get_ports {FPGA_DEBUG_MICB[7]}]
set_property PACKAGE_PIN AH2     [get_ports {FPGA_DEBUG_MICB[8]}]
set_property PACKAGE_PIN AJ1     [get_ports {FPGA_DEBUG_MICB[9]}]
set_property PACKAGE_PIN AD1     [get_ports {FPGA_DEBUG_MICB[10]}]
set_property PACKAGE_PIN AE1     [get_ports {FPGA_DEBUG_MICB[11]}]
set_property PACKAGE_PIN AG1     [get_ports {FPGA_DEBUG_MICB[12]}]
set_property PACKAGE_PIN AH1     [get_ports {FPGA_DEBUG_MICB[13]}]
set_property PACKAGE_PIN AD5     [get_ports {FPGA_DEBUG_MICB[14]}]
set_property PACKAGE_PIN AD4     [get_ports {FPGA_DEBUG_MICB[15]}]
set_property PACKAGE_PIN AH4     [get_ports {FPGA_DEBUG_MICB[16]}]
set_property PACKAGE_PIN AJ4     [get_ports {FPGA_DEBUG_MICB[17]}]
set_property PACKAGE_PIN AD3     [get_ports {FPGA_DEBUG_MICB[18]}]
set_property PACKAGE_PIN AG6     [get_ports {FPGA_DEBUG_MICB[19]}]
set_property PACKAGE_PIN AG5     [get_ports {FPGA_DEBUG_MICB[20]}]
set_property PACKAGE_PIN AF5     [get_ports {FPGA_DEBUG_MICB[21]}]
set_property PACKAGE_PIN AD6     [get_ports {FPGA_DEBUG_MICB[22]}]
set_property PACKAGE_PIN AE6     [get_ports {FPGA_DEBUG_MICB[23]}]
set_property PACKAGE_PIN AF7     [get_ports {FPGA_DEBUG_MICB[24]}]
set_property PACKAGE_PIN AG7     [get_ports {FPGA_DEBUG_MICB[25]}]
set_property PACKAGE_PIN AD8     [get_ports {FPGA_DEBUG_MICB[26]}]
set_property PACKAGE_PIN AH7     [get_ports {FPGA_DEBUG_MICB[27]}]
set_property PACKAGE_PIN AH6     [get_ports {FPGA_DEBUG_MICB[28]}]
set_property PACKAGE_PIN AF9     [get_ports {FPGA_DEBUG_MICB[29]}]
set_property PACKAGE_PIN AF8     [get_ports {FPGA_DEBUG_MICB[30]}]
set_property PACKAGE_PIN AH9     [get_ports {FPGA_DEBUG_MICB[31]}]

set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_DEBUG_HEAD[?]}]
set_property PACKAGE_PIN AN27    [get_ports {FPGA_DEBUG_HEAD[0]}]
set_property PACKAGE_PIN AM27    [get_ports {FPGA_DEBUG_HEAD[1]}]
set_property PACKAGE_PIN AM25    [get_ports {FPGA_DEBUG_HEAD[2]}]
set_property PACKAGE_PIN AL25    [get_ports {FPGA_DEBUG_HEAD[3]}]
set_property PACKAGE_PIN AP26    [get_ports {FPGA_DEBUG_HEAD[4]}]
set_property PACKAGE_PIN AP25    [get_ports {FPGA_DEBUG_HEAD[5]}]
set_property PACKAGE_PIN AJ34    [get_ports {FPGA_DEBUG_HEAD[6]}]


# #############################
# MISC signals
# #############################
set_property IOSTANDARD LVCMOS33 [get_ports {CPLD_FPGA_SPARE[?]}]
set_property PACKAGE_PIN AL24    [get_ports {CPLD_FPGA_SPARE[0]}]
set_property PACKAGE_PIN AP31    [get_ports {CPLD_FPGA_SPARE[1]}]
set_property PACKAGE_PIN AN31    [get_ports {CPLD_FPGA_SPARE[2]}]
set_property PACKAGE_PIN AJ26    [get_ports {CPLD_FPGA_SPARE[3]}]
set_property PACKAGE_PIN AN26    [get_ports {CPLD_FPGA_SPARE[4]}]
set_property PACKAGE_PIN AM26    [get_ports {CPLD_FPGA_SPARE[5]}]
set_property PACKAGE_PIN AK30    [get_ports {CPLD_FPGA_SPARE[6]}]
set_property PACKAGE_PIN AM30    [get_ports {CPLD_FPGA_SPARE[7]}]

set_property IOSTANDARD LVCMOS25 [get_ports {FPGA_LED[?]}]
set_property PACKAGE_PIN AD26    [get_ports {FPGA_LED[1]}]
set_property PACKAGE_PIN AC26    [get_ports {FPGA_LED[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports CALSW_TXRX]
set_property PACKAGE_PIN AB32    [get_ports CALSW_TXRX]
set_property IOSTANDARD LVCMOS33 [get_ports {CALSW[?]}]
set_property PACKAGE_PIN AB29    [get_ports {CALSW[1]}]
set_property PACKAGE_PIN AA29    [get_ports {CALSW[2]}]
set_property PACKAGE_PIN AA25    [get_ports {CALSW[3]}]
set_property PACKAGE_PIN AA24    [get_ports {CALSW[4]}]
set_property PACKAGE_PIN AB25    [get_ports {CALSW[5]}]
set_property PACKAGE_PIN AB24    [get_ports {CALSW[6]}]
set_property PACKAGE_PIN AB30    [get_ports {CALSW[7]}]
set_property PACKAGE_PIN AA30    [get_ports {CALSW[8]}]

set_property IOSTANDARD LVCMOS33 [get_ports {POW_DET_SW[?]}]
set_property PACKAGE_PIN V31     [get_ports {POW_DET_SW[0]}]
set_property PACKAGE_PIN V32     [get_ports {POW_DET_SW[1]}]
set_property PACKAGE_PIN W24     [get_ports {POW_DET_SW[2]}]
set_property PACKAGE_PIN V24     [get_ports {POW_DET_SW[3]}]
set_property PACKAGE_PIN AB27    [get_ports {POW_DET_SW[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {TX_EN[?]}]
set_property PACKAGE_PIN AJ9     [get_ports {TX_EN[0]}]
set_property PACKAGE_PIN AP1     [get_ports {TX_EN[1]}]
set_property PACKAGE_PIN AM2     [get_ports {TX_EN[2]}]
set_property PACKAGE_PIN AM4     [get_ports {TX_EN[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_RXLO_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_RXLO_CS]
set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_RXLO_SDI]
set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_RXLO_SDO]
set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_RXLO_MUTE]
set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_RXLO_REF]
set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_RXLO_STAT]
set_property PACKAGE_PIN AM5     [get_ports LO_CNTRL_3P3_RXLO_CLK]
set_property PACKAGE_PIN AL5     [get_ports LO_CNTRL_3P3_RXLO_CS]
set_property PACKAGE_PIN AK6     [get_ports LO_CNTRL_3P3_RXLO_SDI]
set_property PACKAGE_PIN AJ6     [get_ports LO_CNTRL_3P3_RXLO_SDO]
set_property PACKAGE_PIN AL7     [get_ports LO_CNTRL_3P3_RXLO_MUTE]
set_property PACKAGE_PIN AK7     [get_ports LO_CNTRL_3P3_RXLO_REF]
set_property PACKAGE_PIN AM7     [get_ports LO_CNTRL_3P3_RXLO_STAT]

set_property IOSTANDARD LVCMOS33 [get_ports LMK04308_SYNC]
set_property PACKAGE_PIN AN2     [get_ports LMK04308_SYNC]

set_property IOSTANDARD LVCMOS33 [get_ports CLK_DIST_LD]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_DIST_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_DIST_SDI]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_DIST_CS]
set_property PACKAGE_PIN AL2     [get_ports CLK_DIST_CLK]
set_property PACKAGE_PIN AN3     [get_ports CLK_DIST_CS]
set_property PACKAGE_PIN AM1     [get_ports CLK_DIST_LD]
set_property PACKAGE_PIN AP3     [get_ports CLK_DIST_SDI]

set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_TXLO_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_TXLO_CS]
set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_TXLO_SDI]
set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_TXLO_SDO]
set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_TXLO_MUTE]
set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_TXLO_REF]
set_property IOSTANDARD LVCMOS33 [get_ports LO_CNTRL_3P3_TXLO_STAT]
set_property PACKAGE_PIN AK3     [get_ports LO_CNTRL_3P3_TXLO_CLK]
set_property PACKAGE_PIN AP4     [get_ports LO_CNTRL_3P3_TXLO_CS]
set_property PACKAGE_PIN AN4     [get_ports LO_CNTRL_3P3_TXLO_SDI]
set_property PACKAGE_PIN AK5     [get_ports LO_CNTRL_3P3_TXLO_SDO]
set_property PACKAGE_PIN AJ5     [get_ports LO_CNTRL_3P3_TXLO_MUTE]
set_property PACKAGE_PIN AP5     [get_ports LO_CNTRL_3P3_TXLO_REF]
set_property PACKAGE_PIN AP6     [get_ports LO_CNTRL_3P3_TXLO_STAT]

set_property IOSTANDARD LVCMOS33 [get_ports {BOARD_REV[?]}]
set_property PACKAGE_PIN AC11    [get_ports {BOARD_REV[0]}]
set_property PACKAGE_PIN AF10    [get_ports {BOARD_REV[1]}]
set_property PACKAGE_PIN AE3     [get_ports {BOARD_REV[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports TEMP_SENSE_SCK]
set_property PACKAGE_PIN AE7     [get_ports TEMP_SENSE_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports TEMP_SENSE_CS_N]
set_property PACKAGE_PIN AD9     [get_ports TEMP_SENSE_CS_N]
set_property IOSTANDARD LVCMOS33 [get_ports TEMP_SENSE_SDO]
set_property PACKAGE_PIN AE8     [get_ports TEMP_SENSE_SDO]

set_property IOSTANDARD LVCMOS33 [get_ports ARINC_429_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports ARINC_429_CS_N]
set_property IOSTANDARD LVCMOS33 [get_ports ARINC_429_SDO]
set_property IOSTANDARD LVCMOS33 [get_ports ARINC_429_SDI]
set_property PACKAGE_PIN AF12    [get_ports ARINC_429_SCK]
set_property PACKAGE_PIN AG12    [get_ports ARINC_429_CS_N]
set_property PACKAGE_PIN AG9     [get_ports ARINC_429_SDO]
set_property PACKAGE_PIN AG10    [get_ports ARINC_429_SDI]

set_property IOSTANDARD LVCMOS25 [get_ports SCAL_SYNC_2P5_OUT]
set_property PACKAGE_PIN V1      [get_ports SCAL_SYNC_2P5_OUT]


# ##########################
# LOC
# ##########################
