set_property SRC_FILE_INFO {cfile:/home/murtyms/Radar/HarrisFMCWRadar/HarrisFMCWRadar.srcs/constrs_1/imports/constraints/laysan_rrh_top_pins.xdc rfile:../../../HarrisFMCWRadar.srcs/constrs_1/imports/constraints/laysan_rrh_top_pins.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/murtyms/Radar/HarrisFMCWRadar/HarrisFMCWRadar.srcs/constrs_1/imports/constraints/laysan_rrh_top_clocks.xdc rfile:../../../HarrisFMCWRadar.srcs/constrs_1/imports/constraints/laysan_rrh_top_clocks.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25  [get_ports {ADI_RX?_LVDS_DOUT_?[?]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25  [get_ports {ADI_TX?_LVDS_DIN_?[?]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {CTRL_IN?_2P5_DOUT[?]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {CTRL_OUT?_2P5_DIN[?]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_CLK_OUT?_2P5_IN]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25  [get_ports SCAL_DAT_CLK_OUT?_LVDS_IN_?]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_EN_AGC_IN?_2P5_OUT]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_ENABLE_IN?_2P5_OUT]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_RESET_N_IN?_2P5_OUT]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25  [get_ports SCAL_FB_CLK_IN?_LVDS_OUT_?]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25  [get_ports SCAL_RX_FRM_OUT?_LVDS_IN_?]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25  [get_ports SCAL_TX_FRM_IN?_LVDS_OUT_?]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports SCAL_TXNRX_IN?_2P5_OUT]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports SCAL_DAT_CLK_OUT?_LVDS_IN_?]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports SCAL_RX_FRM_OUT?_LVDS_IN_?]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports ADI_TX?_LVDS_DIN_?]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M7     [get_ports {ADI_RX0_LVDS_DOUT_P[0]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M5     [get_ports {ADI_RX0_LVDS_DOUT_P[1]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1     [get_ports {ADI_RX0_LVDS_DOUT_P[2]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P9     [get_ports {ADI_RX0_LVDS_DOUT_P[3]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P6     [get_ports {ADI_RX0_LVDS_DOUT_P[4]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N9     [get_ports {ADI_RX0_LVDS_DOUT_P[5]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1     [get_ports {ADI_TX0_LVDS_DIN_P[0]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4     [get_ports {ADI_TX0_LVDS_DIN_P[1]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3     [get_ports {ADI_TX0_LVDS_DIN_P[2]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5     [get_ports {ADI_TX0_LVDS_DIN_P[3]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6     [get_ports {ADI_TX0_LVDS_DIN_P[4]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N3     [get_ports {ADI_TX0_LVDS_DIN_P[5]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2     [get_ports {CTRL_IN0_2P5_DOUT[0]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R11    [get_ports {CTRL_IN0_2P5_DOUT[1]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2     [get_ports {CTRL_IN0_2P5_DOUT[2]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3     [get_ports {CTRL_IN0_2P5_DOUT[3]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P10    [get_ports {CTRL_OUT0_2P5_DIN[0]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6     [get_ports {CTRL_OUT0_2P5_DIN[1]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T8     [get_ports {CTRL_OUT0_2P5_DIN[2]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y10    [get_ports {CTRL_OUT0_2P5_DIN[3]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7     [get_ports {CTRL_OUT0_2P5_DIN[4]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W10    [get_ports {CTRL_OUT0_2P5_DIN[5]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T7     [get_ports {CTRL_OUT0_2P5_DIN[6]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R10    [get_ports {CTRL_OUT0_2P5_DIN[7]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB4    [get_ports SCAL_CLK_OUT0_2P5_IN]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5     [get_ports SCAL_DAT_CLK_OUT0_LVDS_IN_P]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1     [get_ports SCAL_EN_AGC_IN0_2P5_OUT]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8     [get_ports SCAL_ENABLE_IN0_2P5_OUT]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U10    [get_ports SCAL_FB_CLK_IN0_LVDS_OUT_P]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9     [get_ports SCAL_RESET_N_IN0_2P5_OUT]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8     [get_ports SCAL_RX_FRM_OUT0_LVDS_IN_P]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4     [get_ports SCAL_SPI_CLK_OUT0_2P5_IN]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W9     [get_ports SCAL_SPI_DI_OUT0_2P5_IN]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2     [get_ports SCAL_SPI_DO_IN0_2P5_OUT]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U11    [get_ports SCAL_SPI_EN_N_OUT0_2P5_IN]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9     [get_ports SCAL_TX_FRM_IN0_LVDS_OUT_P]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5     [get_ports SCAL_TXNRX_IN0_2P5_OUT]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11    [get_ports {ADI_RX1_LVDS_DOUT_P[0]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K10    [get_ports {ADI_RX1_LVDS_DOUT_P[1]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K7     [get_ports {ADI_RX1_LVDS_DOUT_P[2]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J4     [get_ports {ADI_RX1_LVDS_DOUT_P[3]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G10    [get_ports {ADI_RX1_LVDS_DOUT_P[4]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H1     [get_ports {ADI_RX1_LVDS_DOUT_P[5]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7     [get_ports {ADI_TX1_LVDS_DIN_P[0]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L5     [get_ports {ADI_TX1_LVDS_DIN_P[1]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K11    [get_ports {ADI_TX1_LVDS_DIN_P[2]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H9     [get_ports {ADI_TX1_LVDS_DIN_P[3]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F3     [get_ports {ADI_TX1_LVDS_DIN_P[4]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12    [get_ports {ADI_TX1_LVDS_DIN_P[5]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J5     [get_ports {CTRL_IN1_2P5_DOUT[0]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H12    [get_ports {CTRL_IN1_2P5_DOUT[1]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J8     [get_ports {CTRL_IN1_2P5_DOUT[2]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H7     [get_ports {CTRL_IN1_2P5_DOUT[3]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M10    [get_ports {CTRL_OUT1_2P5_DIN[0]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M11    [get_ports {CTRL_OUT1_2P5_DIN[1]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N8     [get_ports {CTRL_OUT1_2P5_DIN[2]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4     [get_ports {CTRL_OUT1_2P5_DIN[3]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H6     [get_ports {CTRL_OUT1_2P5_DIN[4]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J9     [get_ports {CTRL_OUT1_2P5_DIN[5]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N7     [get_ports {CTRL_OUT1_2P5_DIN[6]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H4     [get_ports {CTRL_OUT1_2P5_DIN[7]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J6     [get_ports SCAL_CLK_OUT1_2P5_IN]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G5     [get_ports SCAL_DAT_CLK_OUT1_LVDS_IN_P]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2     [get_ports SCAL_EN_AGC_IN1_2P5_OUT]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L7     [get_ports SCAL_ENABLE_IN1_2P5_OUT]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L8     [get_ports SCAL_FB_CLK_IN1_LVDS_OUT_P]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3     [get_ports SCAL_RESET_N_IN1_2P5_OUT]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2     [get_ports SCAL_RX_FRM_OUT1_LVDS_IN_P]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H2     [get_ports SCAL_SPI_CLK_OUT1_2P5_IN]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1     [get_ports SCAL_SPI_DI_OUT1_2P5_IN]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G2     [get_ports SCAL_SPI_DO_IN1_2P5_OUT]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H3     [get_ports SCAL_SPI_EN_N_OUT1_2P5_IN]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L10    [get_ports SCAL_TX_FRM_IN1_LVDS_OUT_P]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K1     [get_ports SCAL_TXNRX_IN1_2P5_OUT]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K30    [get_ports {ADI_RX2_LVDS_DOUT_P[0]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H31    [get_ports {ADI_RX2_LVDS_DOUT_P[1]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K23    [get_ports {ADI_RX2_LVDS_DOUT_P[2]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G24    [get_ports {ADI_RX2_LVDS_DOUT_P[3]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L28    [get_ports {ADI_RX2_LVDS_DOUT_P[4]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K31    [get_ports {ADI_RX2_LVDS_DOUT_P[5]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M24    [get_ports {ADI_TX2_LVDS_DIN_P[0]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M25    [get_ports {ADI_TX2_LVDS_DIN_P[1]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G29    [get_ports {ADI_TX2_LVDS_DIN_P[2]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L27    [get_ports {ADI_TX2_LVDS_DIN_P[3]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K25    [get_ports {ADI_TX2_LVDS_DIN_P[4]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J24    [get_ports {ADI_TX2_LVDS_DIN_P[5]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J26    [get_ports {CTRL_IN2_2P5_DOUT[0]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H28    [get_ports {CTRL_IN2_2P5_DOUT[1]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G26    [get_ports {CTRL_IN2_2P5_DOUT[2]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K26    [get_ports {CTRL_IN2_2P5_DOUT[3]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L29    [get_ports {CTRL_OUT2_2P5_DIN[0]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L33    [get_ports {CTRL_OUT2_2P5_DIN[1]}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L23    [get_ports {CTRL_OUT2_2P5_DIN[2]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H27    [get_ports {CTRL_OUT2_2P5_DIN[3]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L34    [get_ports {CTRL_OUT2_2P5_DIN[4]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R26    [get_ports {CTRL_OUT2_2P5_DIN[5]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G27    [get_ports {CTRL_OUT2_2P5_DIN[6]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H26    [get_ports {CTRL_OUT2_2P5_DIN[7]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J28    [get_ports SCAL_CLK_OUT2_2P5_IN]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J29    [get_ports SCAL_DAT_CLK_OUT2_LVDS_IN_P]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H32    [get_ports SCAL_EN_AGC_IN2_2P5_OUT]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L30    [get_ports SCAL_ENABLE_IN2_2P5_OUT]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K33    [get_ports SCAL_FB_CLK_IN2_LVDS_OUT_P]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G34    [get_ports SCAL_RESET_N_IN2_2P5_OUT]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J33    [get_ports SCAL_RX_FRM_OUT2_LVDS_IN_P]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P26    [get_ports SCAL_SPI_CLK_OUT2_2P5_IN]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T24    [get_ports SCAL_SPI_DI_OUT2_2P5_IN]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M26    [get_ports SCAL_SPI_DO_IN2_2P5_OUT]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H33    [get_ports SCAL_SPI_EN_N_OUT2_2P5_IN]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L32    [get_ports SCAL_TX_FRM_IN2_LVDS_OUT_P]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M27    [get_ports SCAL_TXNRX_IN2_2P5_OUT]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R25    [get_ports {ADI_RX3_LVDS_DOUT_P[0]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U29    [get_ports {ADI_RX3_LVDS_DOUT_P[1]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R31    [get_ports {ADI_RX3_LVDS_DOUT_P[2]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N31    [get_ports {ADI_RX3_LVDS_DOUT_P[3]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U25    [get_ports {ADI_RX3_LVDS_DOUT_P[4]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P24    [get_ports {ADI_RX3_LVDS_DOUT_P[5]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M30    [get_ports {ADI_TX3_LVDS_DIN_P[0]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T32    [get_ports {ADI_TX3_LVDS_DIN_P[1]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U26    [get_ports {ADI_TX3_LVDS_DIN_P[2]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T28    [get_ports {ADI_TX3_LVDS_DIN_P[3]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P28    [get_ports {ADI_TX3_LVDS_DIN_P[4]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U31    [get_ports {ADI_TX3_LVDS_DIN_P[5]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N26    [get_ports {CTRL_IN3_2P5_DOUT[0]}]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N28    [get_ports {CTRL_IN3_2P5_DOUT[1]}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD33   [get_ports {CTRL_IN3_2P5_DOUT[2]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE31   [get_ports {CTRL_IN3_2P5_DOUT[3]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N32    [get_ports {CTRL_OUT3_2P5_DIN[0]}]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD30   [get_ports {CTRL_OUT3_2P5_DIN[1]}]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N29    [get_ports {CTRL_OUT3_2P5_DIN[2]}]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE30   [get_ports {CTRL_OUT3_2P5_DIN[3]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG32   [get_ports {CTRL_OUT3_2P5_DIN[4]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N27    [get_ports {CTRL_OUT3_2P5_DIN[5]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M29    [get_ports {CTRL_OUT3_2P5_DIN[6]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF33   [get_ports {CTRL_OUT3_2P5_DIN[7]}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U30    [get_ports SCAL_CLK_OUT3_2P5_IN]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R30    [get_ports SCAL_DAT_CLK_OUT3_LVDS_IN_P]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG34   [get_ports SCAL_EN_AGC_IN3_2P5_OUT]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P34    [get_ports SCAL_ENABLE_IN3_2P5_OUT]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U34    [get_ports SCAL_FB_CLK_IN3_LVDS_OUT_P]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M34    [get_ports SCAL_RESET_N_IN3_2P5_OUT]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T27    [get_ports SCAL_RX_FRM_OUT3_LVDS_IN_P]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N33    [get_ports SCAL_SPI_CLK_OUT3_2P5_IN]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE33   [get_ports SCAL_SPI_DI_OUT3_2P5_IN]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD23   [get_ports SCAL_SPI_DO_IN3_2P5_OUT]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U24    [get_ports SCAL_SPI_EN_N_OUT3_2P5_IN]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T33    [get_ports SCAL_TX_FRM_IN3_LVDS_OUT_P]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P33    [get_ports SCAL_TXNRX_IN3_2P5_OUT]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA3    [get_ports {ADI_RX4_LVDS_DOUT_P[0]}]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC7    [get_ports {ADI_RX4_LVDS_DOUT_P[1]}]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7     [get_ports {ADI_RX4_LVDS_DOUT_P[2]}]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10   [get_ports {ADI_RX4_LVDS_DOUT_P[3]}]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4     [get_ports {ADI_RX4_LVDS_DOUT_P[4]}]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6     [get_ports {ADI_RX4_LVDS_DOUT_P[5]}]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W1     [get_ports {ADI_TX4_LVDS_DIN_P[0]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5     [get_ports {ADI_TX4_LVDS_DIN_P[1]}]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB2    [get_ports {ADI_TX4_LVDS_DIN_P[2]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB7    [get_ports {ADI_TX4_LVDS_DIN_P[3]}]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8     [get_ports {ADI_TX4_LVDS_DIN_P[4]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC4    [get_ports {ADI_TX4_LVDS_DIN_P[5]}]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD24   [get_ports {CTRL_IN4_2P5_DOUT[0]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V3     [get_ports {CTRL_IN4_2P5_DOUT[1]}]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8    [get_ports {CTRL_IN4_2P5_DOUT[2]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC24   [get_ports {CTRL_IN4_2P5_DOUT[3]}]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA7    [get_ports {CTRL_OUT4_2P5_DIN[0]}]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF24   [get_ports {CTRL_OUT4_2P5_DIN[1]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF23   [get_ports {CTRL_OUT4_2P5_DIN[2]}]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE23   [get_ports {CTRL_OUT4_2P5_DIN[3]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y11    [get_ports {CTRL_OUT4_2P5_DIN[4]}]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC9    [get_ports {CTRL_OUT4_2P5_DIN[5]}]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W3     [get_ports {CTRL_OUT4_2P5_DIN[6]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8     [get_ports {CTRL_OUT4_2P5_DIN[7]}]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB5    [get_ports SCAL_CLK_OUT4_2P5_IN]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA5    [get_ports SCAL_DAT_CLK_OUT4_LVDS_IN_P]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG24   [get_ports SCAL_EN_AGC_IN4_2P5_OUT]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH24   [get_ports SCAL_ENABLE_IN4_2P5_OUT]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA10   [get_ports SCAL_FB_CLK_IN4_LVDS_OUT_P]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG25   [get_ports SCAL_RESET_N_IN4_2P5_OUT]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y3     [get_ports SCAL_RX_FRM_OUT4_LVDS_IN_P]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF25   [get_ports SCAL_SPI_CLK_OUT4_2P5_IN]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB11   [get_ports SCAL_SPI_DI_OUT4_2P5_IN]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD25   [get_ports SCAL_SPI_DO_IN4_2P5_OUT]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE25   [get_ports SCAL_SPI_EN_N_OUT4_2P5_IN]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC2    [get_ports SCAL_TX_FRM_IN4_LVDS_OUT_P]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC8    [get_ports SCAL_TXNRX_IN4_2P5_OUT]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V33     [get_ports {GPMC_AD[0]}]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y33     [get_ports {GPMC_AD[1]}]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W34     [get_ports {GPMC_AD[2]}]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y32     [get_ports {GPMC_AD[3]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC34    [get_ports {GPMC_AD[4]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC33    [get_ports {GPMC_AD[5]}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA33    [get_ports {GPMC_AD[6]}]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA32    [get_ports {GPMC_AD[7]}]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC32    [get_ports {GPMC_AD[8]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC31    [get_ports {GPMC_AD[9]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB34    [get_ports {GPMC_AD[10]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA34    [get_ports {GPMC_AD[11]}]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC29    [get_ports {GPMC_AD[12]}]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC28    [get_ports {GPMC_AD[13]}]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA28    [get_ports {GPMC_AD[14]}]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA27    [get_ports {GPMC_AD[15]}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y28     [get_ports {GPMC_A[16]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W33     [get_ports {GPMC_A[17]}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W28     [get_ports {GPMC_A[18]}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V26     [get_ports GPMC_ALE]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB26    [get_ports GPMC_BE_N]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V34     [get_ports GPMC_CE_N]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W29     [get_ports GPMC_CLE]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y30     [get_ports GPMC_CLK]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W31     [get_ports GPMC_CS_N]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W25     [get_ports GPMC_RE_N]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y25     [get_ports GPMC_WAIT]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y26     [get_ports GPMC_WE_N]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_RXCLK]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_TXCLK]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_RXER]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_CRS]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_TXEN]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_RXDV]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports AM3357_GMII2_COL]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {AM3357_GMII2_RXD[?]}]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {AM3357_GMII2_TXD[?]}]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ29    [get_ports AM3357_GMII2_RXCLK]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL30    [get_ports AM3357_GMII2_TXCLK]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ33    [get_ports AM3357_GMII2_RXER]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN34    [get_ports AM3357_GMII2_CRS]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK33    [get_ports AM3357_GMII2_TXEN]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN33    [get_ports AM3357_GMII2_RXDV]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK32    [get_ports AM3357_GMII2_COL]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP34    [get_ports {AM3357_GMII2_RXD[0]}]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL34    [get_ports {AM3357_GMII2_RXD[1]}]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN32    [get_ports {AM3357_GMII2_RXD[2]}]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL33    [get_ports {AM3357_GMII2_RXD[3]}]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ31    [get_ports {AM3357_GMII2_TXD[0]}]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM32    [get_ports {AM3357_GMII2_TXD[1]}]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM34    [get_ports {AM3357_GMII2_TXD[2]}]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK31    [get_ports {AM3357_GMII2_TXD[3]}]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM31    [get_ports {AM3357_GPIO_2[22]}]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL32    [get_ports {AM3357_GPIO_2[23]}]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V27     [get_ports {AM3357_GPIO_2[24]}]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB31    [get_ports {AM3357_GPIO_2[25]}]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ30    [get_ports {AM3357_GPIO_3[17]}]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ24    [get_ports {AM3357_GPIO_3[18]}]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports CPRI0_SFP_RS]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports CPRI?_SFP_TX_FAULT]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports CPRI?_SFP_LOS]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports CPRI?_SFP_TX_DISABLE]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports CPRI?_SFP_ABSENT]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports CPRI?_SFP_RS]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL3  [get_ports CPRI0_SFP_RS]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL4  [get_ports CPRI0_SFP_TX_FAULT]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK1  [get_ports CPRI0_SFP_LOS]
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK2  [get_ports CPRI0_SFP_TX_DISABLE]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN1  [get_ports CPRI0_SFP_ABSENT]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK13 [get_ports CPRI0_OPTICAL_RX_N]
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP13 [get_ports CPRI0_OPTICAL_TX_N]
set_property src_info {type:XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG29    [get_ports CLK_LVDS_FPGA_122MHZ88_1_P]
set_property src_info {type:XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH14    [get_ports CLK_LVDS_FPGA_122MHZ88_0_N]
set_property src_info {type:XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH28    [get_ports CLK_LVDS_FPGA1_30MHZ72_P]
set_property src_info {type:XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE5     [get_ports CLK_25MHZ_FPGA]
set_property src_info {type:XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports REC_CLK_30P72MHZ_?]
set_property src_info {type:XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF29 [get_ports REC_CLK_30P72MHZ_P]
set_property src_info {type:XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE11    [get_ports {SPI_MUX_SEL[0]}]
set_property src_info {type:XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD11    [get_ports {SPI_MUX_SEL[1]}]
set_property src_info {type:XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH11    [get_ports {SPI_MUX_SEL[2]}]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG11    [get_ports {SPI_MUX_SEL[3]}]
set_property src_info {type:XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE10    [get_ports {SPI_MUX_SEL[4]}]
set_property src_info {type:XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W30     [get_ports FPGA_SPI_SCK]
set_property src_info {type:XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y27     [get_ports FPGA_SPI_CSN]
set_property src_info {type:XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V29     [get_ports FPGA_SPI_MOSI]
set_property src_info {type:XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V28     [get_ports FPGA_SPI_MISO]
set_property src_info {type:XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK25    [get_ports FPGA_DEBUG_MIC_CLK]
set_property src_info {type:XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH8     [get_ports FPGA_DEBUG_MICB_CLK]
set_property src_info {type:XDC file:1 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN8     [get_ports {FPGA_DEBUG_MICA[0]}]
set_property src_info {type:XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP10    [get_ports {FPGA_DEBUG_MICA[1]}]
set_property src_info {type:XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN9     [get_ports {FPGA_DEBUG_MICA[2]}]
set_property src_info {type:XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK11    [get_ports {FPGA_DEBUG_MICA[3]}]
set_property src_info {type:XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL27    [get_ports {FPGA_DEBUG_MICA[4]}]
set_property src_info {type:XDC file:1 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP29    [get_ports {FPGA_DEBUG_MICA[5]}]
set_property src_info {type:XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM9     [get_ports {FPGA_DEBUG_MICA[6]}]
set_property src_info {type:XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN6     [get_ports {FPGA_DEBUG_MICA[7]}]
set_property src_info {type:XDC file:1 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ28    [get_ports {FPGA_DEBUG_MICA[8]}]
set_property src_info {type:XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK27    [get_ports {FPGA_DEBUG_MICA[9]}]
set_property src_info {type:XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN11    [get_ports {FPGA_DEBUG_MICA[10]}]
set_property src_info {type:XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP11    [get_ports {FPGA_DEBUG_MICA[11]}]
set_property src_info {type:XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP28    [get_ports {FPGA_DEBUG_MICA[12]}]
set_property src_info {type:XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ8     [get_ports {FPGA_DEBUG_MICA[13]}]
set_property src_info {type:XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM10    [get_ports {FPGA_DEBUG_MICA[14]}]
set_property src_info {type:XDC file:1 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP30    [get_ports {FPGA_DEBUG_MICA[15]}]
set_property src_info {type:XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK10    [get_ports {FPGA_DEBUG_MICA[16]}]
set_property src_info {type:XDC file:1 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL10    [get_ports {FPGA_DEBUG_MICA[17]}]
set_property src_info {type:XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM29    [get_ports {FPGA_DEBUG_MICA[18]}]
set_property src_info {type:XDC file:1 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ25    [get_ports {FPGA_DEBUG_MICA[19]}]
set_property src_info {type:XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL9     [get_ports {FPGA_DEBUG_MICA[20]}]
set_property src_info {type:XDC file:1 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ10    [get_ports {FPGA_DEBUG_MICA[21]}]
set_property src_info {type:XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL28    [get_ports {FPGA_DEBUG_MICA[22]}]
set_property src_info {type:XDC file:1 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM11    [get_ports {FPGA_DEBUG_MICA[23]}]
set_property src_info {type:XDC file:1 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK26    [get_ports {FPGA_DEBUG_MICA[24]}]
set_property src_info {type:XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN29    [get_ports {FPGA_DEBUG_MICA[25]}]
set_property src_info {type:XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP9     [get_ports {FPGA_DEBUG_MICA[26]}]
set_property src_info {type:XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ11    [get_ports {FPGA_DEBUG_MICA[27]}]
set_property src_info {type:XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN28    [get_ports {FPGA_DEBUG_MICA[28]}]
set_property src_info {type:XDC file:1 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL8     [get_ports {FPGA_DEBUG_MICA[29]}]
set_property src_info {type:XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP8     [get_ports {FPGA_DEBUG_MICA[30]}]
set_property src_info {type:XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN7     [get_ports {FPGA_DEBUG_MICA[31]}]
set_property src_info {type:XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF4     [get_ports {FPGA_DEBUG_MICB[0]}]
set_property src_info {type:XDC file:1 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG4     [get_ports {FPGA_DEBUG_MICB[1]}]
set_property src_info {type:XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH3     [get_ports {FPGA_DEBUG_MICB[2]}]
set_property src_info {type:XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ3     [get_ports {FPGA_DEBUG_MICB[3]}]
set_property src_info {type:XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF3     [get_ports {FPGA_DEBUG_MICB[4]}]
set_property src_info {type:XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG2     [get_ports {FPGA_DEBUG_MICB[5]}]
set_property src_info {type:XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE2     [get_ports {FPGA_DEBUG_MICB[6]}]
set_property src_info {type:XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF2     [get_ports {FPGA_DEBUG_MICB[7]}]
set_property src_info {type:XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH2     [get_ports {FPGA_DEBUG_MICB[8]}]
set_property src_info {type:XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ1     [get_ports {FPGA_DEBUG_MICB[9]}]
set_property src_info {type:XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD1     [get_ports {FPGA_DEBUG_MICB[10]}]
set_property src_info {type:XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE1     [get_ports {FPGA_DEBUG_MICB[11]}]
set_property src_info {type:XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG1     [get_ports {FPGA_DEBUG_MICB[12]}]
set_property src_info {type:XDC file:1 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH1     [get_ports {FPGA_DEBUG_MICB[13]}]
set_property src_info {type:XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD5     [get_ports {FPGA_DEBUG_MICB[14]}]
set_property src_info {type:XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD4     [get_ports {FPGA_DEBUG_MICB[15]}]
set_property src_info {type:XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH4     [get_ports {FPGA_DEBUG_MICB[16]}]
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ4     [get_ports {FPGA_DEBUG_MICB[17]}]
set_property src_info {type:XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD3     [get_ports {FPGA_DEBUG_MICB[18]}]
set_property src_info {type:XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG6     [get_ports {FPGA_DEBUG_MICB[19]}]
set_property src_info {type:XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG5     [get_ports {FPGA_DEBUG_MICB[20]}]
set_property src_info {type:XDC file:1 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF5     [get_ports {FPGA_DEBUG_MICB[21]}]
set_property src_info {type:XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD6     [get_ports {FPGA_DEBUG_MICB[22]}]
set_property src_info {type:XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE6     [get_ports {FPGA_DEBUG_MICB[23]}]
set_property src_info {type:XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF7     [get_ports {FPGA_DEBUG_MICB[24]}]
set_property src_info {type:XDC file:1 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG7     [get_ports {FPGA_DEBUG_MICB[25]}]
set_property src_info {type:XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD8     [get_ports {FPGA_DEBUG_MICB[26]}]
set_property src_info {type:XDC file:1 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH7     [get_ports {FPGA_DEBUG_MICB[27]}]
set_property src_info {type:XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH6     [get_ports {FPGA_DEBUG_MICB[28]}]
set_property src_info {type:XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF9     [get_ports {FPGA_DEBUG_MICB[29]}]
set_property src_info {type:XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF8     [get_ports {FPGA_DEBUG_MICB[30]}]
set_property src_info {type:XDC file:1 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH9     [get_ports {FPGA_DEBUG_MICB[31]}]
set_property src_info {type:XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN27    [get_ports {FPGA_DEBUG_HEAD[0]}]
set_property src_info {type:XDC file:1 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM27    [get_ports {FPGA_DEBUG_HEAD[1]}]
set_property src_info {type:XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM25    [get_ports {FPGA_DEBUG_HEAD[2]}]
set_property src_info {type:XDC file:1 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL25    [get_ports {FPGA_DEBUG_HEAD[3]}]
set_property src_info {type:XDC file:1 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP26    [get_ports {FPGA_DEBUG_HEAD[4]}]
set_property src_info {type:XDC file:1 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP25    [get_ports {FPGA_DEBUG_HEAD[5]}]
set_property src_info {type:XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ34    [get_ports {FPGA_DEBUG_HEAD[6]}]
set_property src_info {type:XDC file:1 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL24    [get_ports {CPLD_FPGA_SPARE[0]}]
set_property src_info {type:XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP31    [get_ports {CPLD_FPGA_SPARE[1]}]
set_property src_info {type:XDC file:1 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN31    [get_ports {CPLD_FPGA_SPARE[2]}]
set_property src_info {type:XDC file:1 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ26    [get_ports {CPLD_FPGA_SPARE[3]}]
set_property src_info {type:XDC file:1 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN26    [get_ports {CPLD_FPGA_SPARE[4]}]
set_property src_info {type:XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM26    [get_ports {CPLD_FPGA_SPARE[5]}]
set_property src_info {type:XDC file:1 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK30    [get_ports {CPLD_FPGA_SPARE[6]}]
set_property src_info {type:XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM30    [get_ports {CPLD_FPGA_SPARE[7]}]
set_property src_info {type:XDC file:1 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD26    [get_ports {FPGA_LED[1]}]
set_property src_info {type:XDC file:1 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC26    [get_ports {FPGA_LED[2]}]
set_property src_info {type:XDC file:1 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB32    [get_ports CALSW_TXRX]
set_property src_info {type:XDC file:1 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB29    [get_ports {CALSW[1]}]
set_property src_info {type:XDC file:1 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA29    [get_ports {CALSW[2]}]
set_property src_info {type:XDC file:1 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA25    [get_ports {CALSW[3]}]
set_property src_info {type:XDC file:1 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA24    [get_ports {CALSW[4]}]
set_property src_info {type:XDC file:1 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB25    [get_ports {CALSW[5]}]
set_property src_info {type:XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB24    [get_ports {CALSW[6]}]
set_property src_info {type:XDC file:1 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB30    [get_ports {CALSW[7]}]
set_property src_info {type:XDC file:1 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA30    [get_ports {CALSW[8]}]
set_property src_info {type:XDC file:1 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V31     [get_ports {POW_DET_SW[0]}]
set_property src_info {type:XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V32     [get_ports {POW_DET_SW[1]}]
set_property src_info {type:XDC file:1 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W24     [get_ports {POW_DET_SW[2]}]
set_property src_info {type:XDC file:1 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V24     [get_ports {POW_DET_SW[3]}]
set_property src_info {type:XDC file:1 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB27    [get_ports {POW_DET_SW[4]}]
set_property src_info {type:XDC file:1 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ9     [get_ports {TX_EN[0]}]
set_property src_info {type:XDC file:1 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP1     [get_ports {TX_EN[1]}]
set_property src_info {type:XDC file:1 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM2     [get_ports {TX_EN[2]}]
set_property src_info {type:XDC file:1 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM4     [get_ports {TX_EN[3]}]
set_property src_info {type:XDC file:1 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM5     [get_ports LO_CNTRL_3P3_RXLO_CLK]
set_property src_info {type:XDC file:1 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL5     [get_ports LO_CNTRL_3P3_RXLO_CS]
set_property src_info {type:XDC file:1 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK6     [get_ports LO_CNTRL_3P3_RXLO_SDI]
set_property src_info {type:XDC file:1 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ6     [get_ports LO_CNTRL_3P3_RXLO_SDO]
set_property src_info {type:XDC file:1 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL7     [get_ports LO_CNTRL_3P3_RXLO_MUTE]
set_property src_info {type:XDC file:1 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK7     [get_ports LO_CNTRL_3P3_RXLO_REF]
set_property src_info {type:XDC file:1 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM7     [get_ports LO_CNTRL_3P3_RXLO_STAT]
set_property src_info {type:XDC file:1 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN2     [get_ports LMK04308_SYNC]
set_property src_info {type:XDC file:1 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL2     [get_ports CLK_DIST_CLK]
set_property src_info {type:XDC file:1 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN3     [get_ports CLK_DIST_CS]
set_property src_info {type:XDC file:1 line:534 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM1     [get_ports CLK_DIST_LD]
set_property src_info {type:XDC file:1 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP3     [get_ports CLK_DIST_SDI]
set_property src_info {type:XDC file:1 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK3     [get_ports LO_CNTRL_3P3_TXLO_CLK]
set_property src_info {type:XDC file:1 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP4     [get_ports LO_CNTRL_3P3_TXLO_CS]
set_property src_info {type:XDC file:1 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN4     [get_ports LO_CNTRL_3P3_TXLO_SDI]
set_property src_info {type:XDC file:1 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK5     [get_ports LO_CNTRL_3P3_TXLO_SDO]
set_property src_info {type:XDC file:1 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ5     [get_ports LO_CNTRL_3P3_TXLO_MUTE]
set_property src_info {type:XDC file:1 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP5     [get_ports LO_CNTRL_3P3_TXLO_REF]
set_property src_info {type:XDC file:1 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP6     [get_ports LO_CNTRL_3P3_TXLO_STAT]
set_property src_info {type:XDC file:1 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC11    [get_ports {BOARD_REV[0]}]
set_property src_info {type:XDC file:1 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF10    [get_ports {BOARD_REV[1]}]
set_property src_info {type:XDC file:1 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE3     [get_ports {BOARD_REV[2]}]
set_property src_info {type:XDC file:1 line:558 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE7     [get_ports TEMP_SENSE_SCK]
set_property src_info {type:XDC file:1 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD9     [get_ports TEMP_SENSE_CS_N]
set_property src_info {type:XDC file:1 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE8     [get_ports TEMP_SENSE_SDO]
set_property src_info {type:XDC file:1 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF12    [get_ports ARINC_429_SCK]
set_property src_info {type:XDC file:1 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG12    [get_ports ARINC_429_CS_N]
set_property src_info {type:XDC file:1 line:570 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG9     [get_ports ARINC_429_SDO]
set_property src_info {type:XDC file:1 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG10    [get_ports ARINC_429_SDI]
set_property src_info {type:XDC file:1 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1      [get_ports SCAL_SYNC_2P5_OUT]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.13799953460693360 -name SCAL_DAT_CLK_OUT0_LVDS_IN_P -waveform {0 4.06899976730346680} [get_ports SCAL_DAT_CLK_OUT0_LVDS_IN_P]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.13799953460693360 -name SCAL_DAT_CLK_OUT1_LVDS_IN_P -waveform {0 4.06899976730346680} [get_ports SCAL_DAT_CLK_OUT1_LVDS_IN_P]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.13799953460693360 -name SCAL_DAT_CLK_OUT2_LVDS_IN_P -waveform {0 4.06899976730346680} [get_ports SCAL_DAT_CLK_OUT2_LVDS_IN_P]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.13799953460693360 -name SCAL_DAT_CLK_OUT3_LVDS_IN_P -waveform {0 4.06899976730346680} [get_ports SCAL_DAT_CLK_OUT3_LVDS_IN_P]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.13799953460693360 -name SCAL_DAT_CLK_OUT4_LVDS_IN_P -waveform {0 4.06899976730346680} [get_ports SCAL_DAT_CLK_OUT4_LVDS_IN_P]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8 -name AM3357_GMII2_TXCLK -waveform {0 4} [get_ports AM3357_GMII2_TXCLK]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name FPGA_DEBUG_MIC_CLK -source [get_pins BOARD_SUPPORT_i/DEBUG_BLOCK_I/MIC_CLK_GEN/C] -divide_by 1 -invert [get_ports FPGA_DEBUG_MIC_CLK]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -clock_fall -min -add_delay 1.5 [get_ports {ADI_RX?_LVDS_DOUT_N[*]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -clock_fall -max -add_delay 2.5 [get_ports {ADI_RX?_LVDS_DOUT_N[*]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -min -add_delay 1.5 [get_ports {ADI_RX?_LVDS_DOUT_N[*]}]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -max -add_delay 2.5 [get_ports {ADI_RX?_LVDS_DOUT_N[*]}]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -clock_fall -min -add_delay 1.5 [get_ports {ADI_RX?_LVDS_DOUT_P[*]}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -clock_fall -max -add_delay 2.5 [get_ports {ADI_RX?_LVDS_DOUT_P[*]}]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -min -add_delay 1.5 [get_ports {ADI_RX?_LVDS_DOUT_P[*]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -max -add_delay 2.5 [get_ports {ADI_RX?_LVDS_DOUT_P[*]}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -clock_fall -min -add_delay 1.5 [get_ports SCAL_TX_FRM_IN?_LVDS_OUT_N]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -clock_fall -max -add_delay 2.5 [get_ports SCAL_TX_FRM_IN?_LVDS_OUT_N]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -min -add_delay 1.5 [get_ports SCAL_TX_FRM_IN?_LVDS_OUT_N]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -max -add_delay 2.5 [get_ports SCAL_TX_FRM_IN?_LVDS_OUT_N]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -clock_fall -min -add_delay 1.5 [get_ports SCAL_TX_FRM_IN?_LVDS_OUT_P]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -clock_fall -max -add_delay 2.5 [get_ports SCAL_TX_FRM_IN?_LVDS_OUT_P]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -min -add_delay 1.5 [get_ports SCAL_TX_FRM_IN?_LVDS_OUT_P]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -max -add_delay 2.5 [get_ports SCAL_TX_FRM_IN?_LVDS_OUT_P]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -min -add_delay 1.5 [get_ports SCAL_ENABLE_IN?_2P5_OUT]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK_LVDS_FPGA_122MHZ88_1_P] -max -add_delay 2.5 [get_ports SCAL_ENABLE_IN?_2P5_OUT]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {DATA_PROCESSING_i/board_mgmt/hw_control_0/U0/hw_control_struct/mcode1/register0_43_27_reg_inst/latency_gt_0.fd_array[1].reg_comp/fd_prim_array[7].bit_is_0.fdre_comp/C}] -to [get_ports SCAL_ENABLE_IN?_2P5_OUT]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -filter {name =~ *cpri_shared_alignment_i/tx_sync_i/PHASE_ALIGNMENT_DONE_reg*}] -to [get_cells -hier -filter {name =~ *cpri_shared_clocks_i/tx_phase_alignment_done_sync_i/async_rst*_reg*}]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -filter {name =~ *cpri_shared_clocks_i/reset_phalignment_out_reg}] -to [get_cells -hier -filter {name =~ *cpri_shared_alignment_i/tx_sync_i/sync_RESET_PHALIGNMENT/data_sync0_i}]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -filter {name =~ *cpri_shared_clocks_i/tx_sync_rst_reg_inv}]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins {LAYSAN_CPRI_I/CPRI_BLOCK_I/cpri_i/U0/cpri_i/cpri_options.cpri_i/tx_modules_I/TX_ETH_INST.tx_ethernet_i/tx_eth_mii_I/rx_eth_ignore_tx_en_sync_i/data_sync0_i/D} ]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {LAYSAN_CPRI_I/CPRI_BLOCK_I/cpri_i/U0/cpri_i/cpri_options.cpri_i/mgmnt_i/jam_bytes_int_reg[*]/C} ] -to   [get_pins {LAYSAN_CPRI_I/CPRI_BLOCK_I/cpri_i/U0/cpri_i/cpri_options.cpri_i/rx_modules_I/RX_ETH_INST.rx_ethernet_I/rx_eth_mii_I/jam_count_reg[*]/D}]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins LAYSAN_CPRI_I/CPRI_AXI_S/tx0_write_axi_x0_reg/D]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins LAYSAN_CPRI_I/CPRI_AXI_S/TX0_I_CPRI_FIFO/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gpf.wrpf/gpf2.prog_full_i_reg/C] -to [get_pins LAYSAN_CPRI_I/CPRI_AXI_S/cpri_0_csl_synchronizer_i/data_sync0_i/D]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins LAYSAN_CPRI_I/CPRI_AXI_S/RX0_I_CPRI_FIFO/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gpf.wrpf/gpf2.prog_full_i_reg/C] -to [get_pins LAYSAN_CPRI_I/CPRI_AXI_S/cpri_0_csl_synchronizer_i1/data_sync0_i/D]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins LAYSAN_CPRI_I/CPRI_AXI_S/CTRL_I_CPRI_FIFO/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gpf.wrpf/gpf2.prog_full_i_reg/C] -to [get_pins LAYSAN_CPRI_I/CPRI_AXI_S/cpri_0_csl_synchronizer_i2/data_sync0_i/D]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {LAYSAN_CPRI_I/CPRI_AXI_S/RX_AXI_FIFO_I/U0/rx_axi_fifo_struct/sr_flop2/register_x0/synth_reg_inst/latency_gt_0.fd_array[1].reg_comp/fd_prim_array[0].bit_is_0.fdre_comp/C}] -to [get_pins LAYSAN_CPRI_I/CPRI_AXI_S/rx_fifo_reset_76_x0_reg/D]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {LAYSAN_CPRI_I/CPRI_AXI_S/RX_AXI_FIFO_I/U0/rx_axi_fifo_struct/sr_flop5/register_x0/synth_reg_inst/latency_gt_0.fd_array[1].reg_comp/fd_prim_array[0].bit_is_0.fdre_comp/C}] -to  [get_pins LAYSAN_CPRI_I/CPRI_AXI_S/rx_fifo_reset_76_ctrl_x0_reg/D]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {reset_iq_if_reg*/C}]
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {rst_reg_x2_reg[31]/C}] -to [get_pins ad9361_sync_reg/D]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {rst_reg_x2_reg[31]/C}] -to [get_pins SCAL_SYNC_2P5_OUT_i_reg/D]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_rx_channel*/i_up_adc_channel/i_adc_xfer_status/up_xfer_toggle_m1_reg/D} ]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_rx_channel*/i_up_adc_channel/i_adc_xfer_status/d_xfer_data_reg[*]/C} ] -to   [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_rx_channel*/i_up_adc_channel/i_adc_xfer_status/up_data_status_reg[*]/D} ]
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_up_adc_common/i_adc_xfer_status/up_xfer_toggle_m1_reg/D} ]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_up_adc_common/i_adc_xfer_status/d_xfer_data_reg[*]/C} ] -to   [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_up_adc_common/i_adc_xfer_status/up_data_status_reg[*]/D} ]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_rx_channel*/i_up_adc_channel/i_adc_xfer_cntrl/d_xfer_toggle_m1_reg/D}]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_rx_channel*/i_up_adc_channel/i_adc_xfer_cntrl/d_data_cntrl_reg[*]/D}]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_up_adc_common/i_adc_xfer_cntrl/d_xfer_toggle_m1_reg/D}]
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_up_adc_common/i_adc_xfer_cntrl/up_xfer_data_reg[*]/C}] -to   [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_up_adc_common/i_adc_xfer_cntrl/d_data_cntrl_reg[*]/D}]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_up_adc_common/i_adc_clock_mon/d_count_toggle_m1_reg/D}]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_up_adc_common/i_adc_clock_mon/up_count_toggle_m1_reg/D}]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_up_adc_common/i_adc_clock_mon/up_d_count_reg[*]/D}]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_up_adc_common/up_resetn_reg/C}] -to   [get_pins {DATA_PROCESSING_i/ad9361_if/radio_block*/axi_ad9361_0/inst/i_rx/i_up_adc_common/i_adc_rst_reg/i_rst_reg/PRE}]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins LAYSAN_CPRI_I/CPRI_BLOCK_I/tready_not_sync_i_reg/C]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {DATA_PROCESSING_i/board_mgmt/hw_control_0/U0/hw_control_struct/mcode1/register38_57_28_reg[*]/C}]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_pins {rst_reg_x2_reg[4]/C}] -to [get_pins LAYSAN_CPRI_I/CPRI_BLOCK_I/tready_not_sync_i_reg/D] 13.020 -datapath_only
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_pins {DATA_PROCESSING_i/board_mgmt/hw_control_0/U0/hw_control_struct/mcode1/register34_56_28_reg[*]/C}] -to [get_pins LAYSAN_CPRI_I/CPRI_BLOCK_I/basic_frm_sync_reg/D] 13.020 -datapath_only
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {DATA_PROCESSING_i/board_mgmt/hw_control_0/U0/hw_control_struct/mcode1/register34_56_28_reg[4]/C}] -to [get_pins LAYSAN_CPRI_I/CPRI_BLOCK_I/basic_frm_sync_reg/D]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {rst_reg_x2_reg[4]/C}] -to [get_pins LAYSAN_CPRI_I/CPRI_BLOCK_I/tready_not_sync_i_reg/D]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins LAYSAN_CPRI_I/CPRI_BLOCK_I/tready_not_sync_i_reg/C]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {DATA_PROCESSING_i/board_mgmt/hw_control_0/U0/hw_control_struct/mcode1/register38_57_28_reg[*]/C}]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_pins {rst_reg_x2_reg[4]/C}] -to [get_pins LAYSAN_CPRI_I/CPRI_BLOCK_I/tready_not_sync_i_reg/D] 13.020 -datapath_only
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_pins {DATA_PROCESSING_i/board_mgmt/hw_control_0/U0/hw_control_struct/mcode1/register34_56_28_reg[*]/C}] -to [get_pins LAYSAN_CPRI_I/CPRI_BLOCK_I/basic_frm_sync_reg/D] 13.020 -datapath_only
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {DATA_PROCESSING_i/board_mgmt/hw_control_0/U0/hw_control_struct/mcode1/register34_56_28_reg[4]/C}] -to [get_pins LAYSAN_CPRI_I/CPRI_BLOCK_I/basic_frm_sync_reg/D]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {rst_reg_x2_reg[4]/C}] -to [get_pins LAYSAN_CPRI_I/CPRI_BLOCK_I/tready_not_sync_i_reg/D]
