# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/laysan_rrh_top_pins.xdc

# XDC: imports/constraints/laysan_rrh_top_clocks.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_gpmc_axi_bridge_0_1/design_1_gpmc_axi_bridge_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_gpmc_axi_bridge_0_1 || ORIG_REF_NAME==design_1_gpmc_axi_bridge_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ad9361_spi_generic_0_0/design_1_ad9361_spi_generic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ad9361_spi_generic_0_0 || ORIG_REF_NAME==design_1_ad9361_spi_generic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ad9361_spi_generic_0_1/design_1_ad9361_spi_generic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ad9361_spi_generic_0_1 || ORIG_REF_NAME==design_1_ad9361_spi_generic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ad9361_spi_generic_1_0/design_1_ad9361_spi_generic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ad9361_spi_generic_1_0 || ORIG_REF_NAME==design_1_ad9361_spi_generic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ad9361_spi_generic_2_0/design_1_ad9361_spi_generic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ad9361_spi_generic_2_0 || ORIG_REF_NAME==design_1_ad9361_spi_generic_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ad9361_spi_generic_3_1/design_1_ad9361_spi_generic_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ad9361_spi_generic_3_1 || ORIG_REF_NAME==design_1_ad9361_spi_generic_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_crossbar_0_0/design_1_axi_crossbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_crossbar_0_0 || ORIG_REF_NAME==design_1_axi_crossbar_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Blinky_0_0/design_1_Blinky_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Blinky_0_0 || ORIG_REF_NAME==design_1_Blinky_0_0} -quiet] -quiet

# XDC: /home/murtyms/Radar/HarrisFMCWRadar/HarrisFMCWRadar.gen/sources_1/bd/design_1/design_1_ooc.xdc
